# Hero Project Configuration
# On-Device AI: The Small Language Models Revolution

# Model Configuration
model:
  name: "Qwen/Qwen2-VL-7B-Instruct"
  max_tokens: 512
  temperature: 0.7
  device: "auto"  # auto, cpu, cuda, mps

# Vector Store Configuration
vector_store:
  persist_directory: "./chroma_db"
  collection_name: "knowledge_base"
  embedding_model: "all-MiniLM-L6-v2"
  search_results: 3

# Agent Configuration
agents:
  rag:
    system_prompt: "You are a helpful AI assistant with access to a knowledge base. Provide clear, concise answers based on the retrieved context."
    max_context_length: 2000
  
  task:
    system_prompt: "You are a task automation assistant. Execute tasks using available tools and provide clear results."
    available_tools: ["file_read", "file_write", "web_search"]

# UI Configuration
ui:
  gradio:
    port: 7860
    share: false
    debug: false
  
  jupyter:
    port: 8888
    allow_root: false

# Performance Configuration
performance:
  batch_size: 1
  num_workers: 1
  cache_models: true
  optimize_memory: true